// <auto-generated />
namespace MedAssist.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class portedtoazure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(portedtoazure));
        
        string IMigrationMetadata.Id
        {
            get { return "201707281827510_ported-to-azure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
